### PR TITLE
Store version content automatically once in preparation for parsing change

### PR DESCRIPTION
**Pull request by bosschaert**
## Description

In preparation for the parsing changes coming to da-collab https://github.com/adobe/da-collab/pull/38 and da-live https://github.com/adobe/da-collab/pull/38 store the content of a document automatically once.

## Related Issue

#6 

## Motivation and Context

Right now versions are only stored when a user explicitly requests this.

## How Has This Been Tested?

Locally with da-live and da-collab. 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by auniverseaway — CHANGES_REQUESTED** [review]
I would prefer if we were more deliberate about when we make versions.

1. Every Helix preview
2. On demand

From a docs / predictability standpoint, I don't think we want to get into the randomness of when a version would be created.

"Why did it make a version at this time?"
"Oh, we randomly make versions 'now and then'"

**Comment by bosschaert** [comment]
Thanks for the thoughts @auniverseaway . This would obviously be in addition to any explicit version creation operations. If you look at other document authoring systems they do seem to create versions automatically every now and then so that there is a history to go back through without the need for the user to explicitly create versions.

But I left the PR draft deliberately to have a discussion. Maybe previewing a document is enough of a cue for an additional version creation event.

**Comment by bosschaert** [comment]
With https://github.com/adobe/da-live/pull/110/commits/0dd88b0dfafcc56629b996b25a694d43b8a2548e#diff-2f1d9ac34dc38306a1ca727a924a5a2cf67637ab7390350fe2845a9ce524b5f3R44 I have implemented a version save on every preview.

**Comment by bosschaert** [comment]
Converting this one to draft, as we may not need this in the end.

**Review by auniverseaway — APPROVED** [review]

**Review by auniverseaway — APPROVED** [review]
I may be missing something, but it might be nice to label these first-time versions something... `Collab Parse` (do whatever you think is best). Then if something does go wrong, we can search / scan for these more easily.

**Pull request merged**
