### PR TITLE
GH-68 - Move API

### PR DESCRIPTION
**Pull request by auniverseaway**
* Rename / Move is faster (more concurrent)
* Server-side API handles trying to rename / move a parent into a child.
* Server-side API handles trying to rename / move to the same location as the original source (add a timestamp)
* Rename / move is more reliable. If a file is moved, it should never exist anywhere else.
* Can reliably handle 10,000 documents in ~20s.

Resolves: GH-68

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bstopp** [comment]
Is this intended to replace the `rename` API operation? And no changes/updates planned for `copy`?

**Comment by auniverseaway** [comment]
@bstopp correct and correct. Rename can be removed when da-live is updated to use this move API.

I'm trying to keep this isolated as much as possible for now in light of your changes. In the future, we can likely re-use object/copy.

**Comment by bstopp** [comment]
Ok, but this doesn't solve the need for #66 on the Copy API. So that still needs to be merged.

**Comment by auniverseaway** [comment]
Yes. That PR is still valid... I think. I would maybe solve it differently, though.

We should probably iterate through all the objects in the continuation tokens to get a full list of items _then_ do the copy. At least, that's what I would explore at a later date.

Move into a child should be prohibited (which I do in move helper) while copy into a child should be legal... but it would mean getting a snapshot of all items before starting the copy so you don't recursively do that. If your solution works, I think that's great and low effort.

**Comment by bstopp** [comment]
Can discuss on that PR :)

**Review by sukamat — APPROVED** [review]

**Pull request merged**
